{
   "responseStatus": "FAILURE",
   "errors": [   {
      "type": "INSUFFICIENT_ACCESS",
      "message": "Authentication call failed for external service: sfdc:00Dg0000006S7yO!AQ4AQGoMl3zL1A_nWA45c.E8DzjFmxWpODLdS73_GWAheP0Cc8NOBK1.52fWwzDU4ZHPJdO76rwgb.B1PjE78yqoL_JyT.IH:https://gso--qiddev.cs17.my.salesforce.com External System failed to authenticate session."
   }]
}